require "rake/testtask"

# desc 'Test'
# task :test do
#   sh 'ruby ./test/triangles_test.rb'
# end

# desc 'Run File'
# task :run do  
#   sh 'ruby ./lib/triangles.rb'
# end

desc 'Run Tests'
task :default => :test

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList['test/**/*_test.rb']
end